name: Sync Books

on:
  workflow_dispatch:
    inputs:
      isbn:
        description: 'Comma-separated ISBNs to add (e.g. 9781234567890,9780987654321)'
        required: true
        default: ''

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo without default credentials (we’ll use PAT)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Generate isbn_input.json at the repo root
      - name: Generate isbn_input.json
        run: |
          # split on commas, wrap each in quotes
          IFS=',' read -ra ISBN_ARRAY <<< "${{ github.event.inputs.isbn }}"
          printf '{ "isbn": [' > isbn_input.json
          for isbn in "${ISBN_ARRAY[@]}"; do
            clean=$(echo "$isbn" | xargs)
            printf "\"%s\"," "$clean"
          done >> isbn_input.json
          # remove trailing comma, close array
          sed -i 's/,$/ ] }/' isbn_input.json
          cat isbn_input.json

      # 5) Fetch metadata & download covers into books/new_books/ & books/covers/
      - name: Fetch metadata & download covers
        run: python script/isbn_to_book_json.py

      # 6) Publish new books to Notion and move JSONs to books/processed_books/
      - name: Publish to Notion and archive
        run: python script/publish_book.py

      # 7) List how many books have been processed
      - name: List processed count
        run: |
          echo "Processed books in books/processed_books/:"
          ls books/processed_books | wc -l

      # 8) Commit & Push any changes back to the repo using your PAT
      - name: Commit & Push changes
        if: ${{ always() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add isbn_input.json books/new_books books/processed_books
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: persist updated ISBN input and processed lists"
            git push https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }} HEAD:main
          fi
